version: '3.7'

services:
  portfolio:
    container_name: portfolio
    networks:
      - net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6969:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio.rule=Host(`portoflio.matt.quest`)'
      - 'traefik.http.routers.portfolio.entrypoints=https'
      - 'traefik.http.routers.portfolio.tls=true'
      - 'traefik.http.routers.portfolio.tls.certresolver=letsencrypt'
    restart: unless-stopped

networks:
  net:
    name: "net"